<?xml version="1.0" encoding="UTF-8"?><testrun name="TesteService_Conta (1)" project="cursoMassa" tests="4" started="4" failures="0" errors="1" ignored="0">
  <testsuite name="seuBarrigaPontoCom_estrategia5.TesteService_Conta" time="0.058">
    <testcase name="testAlteraConta" classname="seuBarrigaPontoCom_estrategia5.TesteService_Conta" time="0.0"/>
    <testcase name="testConsultarConta" classname="seuBarrigaPontoCom_estrategia5.TesteService_Conta" time="0.0"/>
    <testcase name="testRemoverConta" classname="seuBarrigaPontoCom_estrategia5.TesteService_Conta" time="0.013"/>
    <testcase name="testInserirConta" classname="seuBarrigaPontoCom_estrategia5.TesteService_Conta" time="0.045">
      <error>org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:767)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1659)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:373)
	at br.ce.wcaquino.dao.impl.ContaDAOImpl.findByName(ContaDAOImpl.java:57)
	at br.ce.wcaquino.service.ContaService.findByName(ContaService.java:29)
	at seuBarrigaPontoCom_estrategia5.TesteService_Conta.testInserirConta(TesteService_Conta.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

</error>
    </testcase>
  </testsuite>
</testrun>
